---
# tasks file for nginx
  - name: copy nginx.conf
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: copy default site conf
    copy:
      src: files/default.conf
      dest: /etc/nginx/conf.d/default.conf
