---
# tasks file for nginx
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - import_tasks: copy_conf.yml

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes
