# roles/wordpress/tasks/install.yml
---
  - name: Copy wordpress source to dest
    copy:
      src: files/wordpress-5.4.2.tar.gz
      dest: /var/www/wordpress-5.4.2.tar.gz

  - name: unzip wordpress
    shell: cd /var/www && tar -zxf wordpress-5.4.2.tar.gz

  - name: copy file config to des
    copy:
      src: files/wp-config.php
      dest: /var/www/wordpress/wp-config.php
        
  - name: change mode to wordpress
    file: 
      path: /var/www/wordpress
      owner: nginx
      group: nginx
