---
# tasks file for mariadb
  - name: Install all required dependencies
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - python
      - python-setuptools
      - python-devel
      - python-pip
      - MySQL-python

  - name: Install wget
    yum: 
      name: wget
      state: present
  - name: wget maridb repo
    shell: sudo wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup && sudo chmod +x mariadb_repo_setup && sudo ./mariadb_repo_setup
  - name: Install mariadb 
    yum:
      name: MariaDB-server
      state: present

  - name: Start and enable mariadb
    systemd:
      name: mariadb.service
      state: started
      enabled: yes

  - name: Create database
    mysql_db:
      name: wordpressdb
      state: present

  - name: Create user 
    mysql_user:
      name: wpusr
      password: Passw0rd
      priv: '*.*:ALL'
      state: present
      host: '%'
  - name: Create local user
    mysql_user:
      name: wpusr
      password: Passw0rd
      priv: '*.*:ALL'
      state: present
      host: 'localhost'
