---
  - name: setup wordpress all in 1 for 1 music node
    hosts: uat-3
    roles:
      - { role: common, tags: common }
      - { role: nginx, tags: nginx }
      - { role: php-fpm, tags: php-fpm }
      - { role: mariadb, tags: mariadb }
      - { role: wordpress, tags: wordpress }
