-
  name: Demo test deploy a web application
  hosts: web-2 
  tasks:
    - name: Install all required dependencies
      yum: 
        name: "{{ item }}" 
        state: present
      with_items:
          - python
          - python-setuptools
          - python-devel
          - python-pip
          - MySQL-python

    - name: mysql server
      yum: 
        name: "{{ item }}" 
        state: present
      with_items:
          - mariadb-server
          - mariadb-libs

    - name: Start mysql service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: create database
      mysql_db:
        name: employee_db
        state: present

    - name: create user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'
    - name: Install python flask
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - Flask

    - name: Copy source code
      copy: src=app.py dest=/opt/app.py

    - name: Start web server
      shell: nohup FLASK_APP=/opt/app.py flask run --host=0.0.0.0 &
