---
- name: Install php fpm to Centos 7
  yum: 
    name: '{{item}}'
    state: present
  with_items:
    - php
    - php-mysql
    - php-fpm
- name: Enable and start service php
  service: 
    name: '{{item}}'
    state: started
    enabled: True
  with_items:
